---
title: "FIRST HOMEWORK"
author: "Shawn Wang"
date: "`r format(Sys.Date(), '%B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 1
    css: !expr here::here("./stylesTemplates/sw_1.css")
---

```{r setup, include=F}
knitr::opts_chunk$set(fig.width=8, fig.height=5, fig.align = 'left', fig.path='Figs/', cache.path='Cache/', eval=T, echo=T, tidy=TRUE,  cache=F, message=F, warning=F, stringsAsFactors=F, yaml.eval.expr = TRUE)  

library(xfun)
pkg_attach("tidyverse", "here", "kableExtra", "RCurl", "psych", "knitr", "RColorBrewer", 'dplyr', install=T)

jamie.theme <- theme_bw() + theme(axis.line = element_line(colour = "black"), panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border = element_blank(), panel.background = element_blank(), legend.title= element_blank())  #custom theme ggplot2


print.me <- function(x, ...) {
if (nrow(x) > 200){
   len <- 200 
    } else {
       len <- (nrow(x))
}
   x[1:len,] %>%
   kbl(digits=2, align= 'l', booktabs=T) %>%
   kable_styling(fixed_thead = T) %>%
   kable_paper("striped", full_width = T, html_font = "Helvetica", font_size = 12) %>%
   row_spec(0, color = "white", background = "#5b705f", font_size = 12) %>%
   scroll_box(width = "700px", height = "500px") %>%
   asis_output()
}

registerS3method("knit_print", "data.frame", print.me)
#to_R <- read.csv(here("data", "MyRaw.txt")) ---- using 'here' to read in data
```



# First Task

I am going to create a data frame with string "mary had a little lamb". 

```{r}

#create a data frame with one column named string and value for first row "mary had a little lamb"
df <- data.frame(string = "mary had a little lamb")








kable(df)
```




# Second Task

Then I'm going to split the string into one row per word.

```{r}

#split the string by giving function name the column "string" and indicating delimited by spaces
df_split <- string %>%
  separate_longer_delim(string, delim = " ")
kable(df_split)
```




# Third Task


Then I'm going to add a variable called n_letters that counts the letters of each word.

```{r}

#create new column that counts number of characters in column string
df_split <- df_split %>%
  mutate(n_letters = nchar(string))
kable(df_split)
```




# Fourth Task


Same thing but for the 10,000 repeats
```{r}
string_repeat <- data.frame(repeat_str = paste(rep("mary had a little lamb", 10000), collapse = " "))
string_repeat_split <- string_repeat %>%
  separate_longer_delim(repeat_str, delim = " ") %>%
  mutate(n_letter = nchar(repeat_str))
```


